- CHANGELOG.md
- clinlp/component/qualifier.py
- clinlp/resources/psynlp_context_rules.json
- tests/data/qualifier_rules_simple.json
- tests/unit/test_qualifier.py
* Add a max_scope for context triggers
* Fixed some tests that were not executed
> Max scope context triggers

- README.md
> Update ner docs

- CHANGELOG.md
- README.md
- clinlp/qualifier/__init__.py
- clinlp/qualifier/context_algorithm.py
- clinlp/qualifier/qualifier.py
- clinlp/qualifier/transformer.py
- clinlp/resources/context_rules.json
- tests/data/qualifier_rules_simple.json
- tests/regression/qualifier/test_regression_context_algorithm.py
- tests/regression/qualifier/test_regression_transformer.py
- tests/unit/qualifier/test_context_algorithm.py
- tests/unit/qualifier/test_qualifier.py
- tests/unit/qualifier/test_transformer.py
* Refactored into `Qualifier` and `QualifierFactory` classes
* Can now add additional info (like `prob`) to `Qualifier`
> Refactor qualifier

- CHANGELOG.md
- clinlp/entity.py
- pyproject.toml
- tests/unit/test_entity.py
* Fix bug with overlapping entities, now resolved by taking the longest when overlapping
> Fix overlap bug

- CHANGELOG.md
- README.md
- clinlp/qualifier/__init__.py
- clinlp/qualifier/context_algorithm.py
- clinlp/qualifier/qualifier.py
- clinlp/qualifier/transformer.py
- clinlp/resources/context_rules.json
- pyproject.toml
- tests/data/qualifier_cases.json
- tests/data/qualifier_rules_simple.json
- tests/regression/qualifier/test_regression_context_algorithm.py
- tests/regression/qualifier/test_regression_transformer.py
- tests/unit/qualifier/test_context_algorithm.py
- tests/unit/qualifier/test_qualifier.py
- tests/unit/qualifier/test_transformer.py
* Minor refactor for adding qualifiers
* Now always includes defaults (e.g. affirmed, current, plausible, patient for Context Algorithm)
* Use titlecase (instead of uppercase) for qualifier values (e.g. AFFIRMED -> Affirmed)
> Update qualifier defaults

- CHANGELOG.md
- clinlp/entity.py
- pyproject.toml
- tests/unit/test_entity.py
* Fix bug where adjacent entities were marked as overlapping and thus removed
> Fix adjacent entity bug

- .github/workflows/build.yml
- .github/workflows/format-lint.yml
- .github/workflows/formatting-linting.yml
- .github/workflows/test.yml
- Makefile
- clinlp/language.py
- clinlp/normalizer.py
- clinlp/qualifier/context_algorithm.py
- clinlp/qualifier/qualifier.py
- clinlp/sentencizer.py
- clinlp/util.py
- poetry.lock
- pyproject.toml
- tests/integration/test_integration_normalizer.py
- tests/regression/qualifier/test_regression_context_algorithm.py
- tests/regression/qualifier/test_regression_transformer.py
- tests/regression/test_regression_sentencizer.py
- tests/regression/test_regression_tokenizer.py
- tests/unit/qualifier/test_context_algorithm.py
- tests/unit/qualifier/test_transformer.py
- tests/unit/test_entity.py
- tests/unit/test_language.py
- tests/unit/test_sentencizer.py
- tests/unit/test_util.py
* Changed formatting to `black` and `isort` with config in `pyproject.toml`
* Changed max line length to 88
* Changed linting to `flake8` with config in `pyproject.toml`
* Fixed flake8 issues
* Added testing pipeline
* Added linting and formatting pipeline
> Update repository CI

- README.md
> Add citing info to readme

- clinlp/qualifier/__init__.py
- clinlp/qualifier/transformer.py
- tests/data/qualifier_cases.json
- tests/regression/qualifier/test_regression_transformer_experiencer.py
- tests/regression/qualifier/test_regression_transformer_negation.py
- tests/unit/qualifier/test_transformer.py
Added ExperiencerTransformer, relates to [this](https://github.com/umcu/clinlp/issues/59) issue.
> added ExperiencerTransformer

- .gitignore
- CHANGELOG.md
- README.md
- clinlp/qualifier/__init__.py
- clinlp/qualifier/transformer.py
- pyproject.toml
- tests/data/qualifier_cases.json
- tests/regression/qualifier/test_regression_transformer_experiencer.py
- tests/regression/qualifier/test_regression_transformer_negation.py
- tests/unit/qualifier/test_transformer.py
* Repaire defects tests/pipelines (fixes #74)
* Small refactor for transformer based qualifier detection, reduces some duplicate code (fixes #63)
* Prepare release 0.6.5
> Fix experiencer qualifier

- CHANGELOG.md
- README.md
- src/clinlp/ie/qualifier/context_algorithm.py
- src/clinlp/ie/qualifier/qualifier.py
- src/clinlp/metrics/__init__.py
- src/clinlp/util.py
- tests/unit/ie/qualifier/test_context_algorithm.py
- tests/unit/ie/qualifier/test_qualifier.py
- tests/unit/test_util.py
* Added support for non-binary qualifiers to the Context Algorithm. Resolves conflicts by looking at the closest modifier, than check the priority attribute.
> Non binary qualifier support for Context Algorithm

- CHANGELOG.md
- src/clinlp/ie/entity.py
- src/clinlp/ie/qualifier/context_algorithm.py
- src/clinlp/ie/qualifier/transformer.py
- src/clinlp/normalizer.py
- src/clinlp/sentencizer.py
- src/clinlp/util.py
- tests/unit/test_util.py
* Changed `clinlp_autocomponent` to `clinlp_component`, which automatically registers your component with spaCy
> Simlify clinlp component

- CHANGELOG.md
- poetry.lock
- pyproject.toml
- src/clinlp/ie/entity.py
- src/clinlp/ie/qualifier/transformer.py
* Prepare release
* Update dependencies
* Renamed the `other_threshold` config to `family_threshold` in the `clinlp_experiencer_transformer` component
* Minor improvements
> Prepare release and minor fixes

- README.md
> Add spaCy badge

- CHANGELOG.md
- CONTRIBUTING.md
- Makefile
- README.md
- docs/emojize.py
- docs/source/changelog.md
- docs/source/contributing.md
- docs/source/index.md
* Add contributing guidelines
* Add emojize script for emojis in docs
* Reformatted changelog for consistency
> Add contributing guidelines

- CHANGELOG.md
- src/clinlp/ie/entity.py
- src/clinlp/ie/qualifier/context_algorithm.py
- src/clinlp/ie/qualifier/transformer.py
- src/clinlp/normalizer.py
- src/clinlp/sentencizer.py
- src/clinlp/util.py
- tests/unit/test_util.py
* Simplified defaults for components
> Improve default settings

- CHANGELOG.md
- data/mantra_gsc.json
- docs/source/data.md
- docs/source/metrics.md
- scripts/mantra_gsc.py
- src/clinlp/metrics/ie.py
- tests/unit/metrics/test_ie.py
- Made qualifiers in metrics optional in the `Annotation` class
- Added the Mantra GSC dataset, so it can be used for evaluation
N/a
Yes
Yes
N/a
> Add mantra data

- CHANGELOG.md
- poetry.lock
- pyproject.toml
* Prepare release 0.9.0
* Update dependencies
N/a
Yes
Yes
N/a
> Prepare release

- uv.lock
Please provide a clear and concise description and motivation of the proposed change.
If this pull request is related to an issue, please provide a link to the issue here.
Yes/no
Yes/no
Add any other context about the pull request here.
> Update uv lock

- .github/workflows/build.yml
- .github/workflows/format-lint.yml
- .github/workflows/test.yml
- CHANGELOG.md
- pyproject.toml
- uv.lock
* Fixed inclusion of resource in package
* Fixed building pipeline, which didn't pick up this error
N/a
Yes
Yes
N/a
> Fix resource including

- .github/workflows/build.yml
- Fix build artifact path in build pipeline
> Fix build artifact path

- CHANGELOG.md
- docs/source/apps.md
- docs/source/index.md
- pyproject.toml
- src/clinlp/__init__.py
- src/clinlp/cli.py
- src/clinlp_apps/ie_demo/README.md
- src/clinlp_apps/ie_demo/app.py
- src/clinlp_apps/ie_demo/resources/sample_terms.json
- src/clinlp_apps/ie_demo/resources/sample_text.txt
- src/clinlp_apps/ie_demo/src/__init__.py
- src/clinlp_apps/ie_demo/src/controller.py
- src/clinlp_apps/ie_demo/src/model.py
- src/clinlp_apps/ie_demo/src/utils.py
- src/clinlp_apps/ie_demo/src/view.py
- uv.lock
Add a visual/interactive demo for Information Extraction pipeline (start using `clinlp app ie_demo`)
#57 
Yes
Yes
N/a
> Add ie visual demo
